version: '3.8'

services:
  owncloud1:
    image: owncloud/server:latest
    container_name: owncloud1
    restart: always
    environment:
      - OWNCLOUD_DOMAIN=ikaz.cloud
      - OWNCLOUD_TRUSTED_DOMAINS=ikaz.cloud
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_ADMIN_USERNAME=admin
      - OWNCLOUD_ADMIN_PASSWORD=admin
    networks:
      - owncloud_net

  owncloud2:
    image: owncloud/server:latest
    container_name: owncloud2
    restart: always
    environment:
      - OWNCLOUD_DOMAIN=ikaz.cloud
      - OWNCLOUD_TRUSTED_DOMAINS=ikaz.cloud
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_ADMIN_USERNAME=admin
      - OWNCLOUD_ADMIN_PASSWORD=admin
    networks:
      - owncloud_net

  owncloud3:
    image: owncloud/server:latest
    container_name: owncloud3
    restart: always
    environment:
      - OWNCLOUD_DOMAIN=ikaz.cloud
      - OWNCLOUD_TRUSTED_DOMAINS=ikaz.cloud
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_ADMIN_USERNAME=admin
      - OWNCLOUD_ADMIN_PASSWORD=admin
    networks:
      - owncloud_net

  mariadb:
    image: mariadb:10.11 # minimum required ownCloud version is 10.9
    container_name: owncloud_mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=owncloud
      - MYSQL_USER=owncloud
      - MYSQL_PASSWORD=owncloud
      - MYSQL_DATABASE=owncloud
      - MARIADB_AUTO_UPGRADE=1
    networks:
      - owncloud_net

  redis:
    image: redis:6
    container_name: owncloud_redis
    restart: always
    command: ["--databases", "1"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - owncloud_net


  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=root 
      - PMA_PASSWORD=root
    networks:
      - owncloud_net

  nginx-lb:
    image: nginx:latest
    container_name: load_balancer
    restart: always
    volumes:
      - ./nginx/nginx-lb.conf:/etc/nginx/nginx.conf:ro
    networks:
      - owncloud_net

  reverse-proxy:
    image: nginx:latest
    container_name: reverse_proxy
    restart: always
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - nginx-lb
    networks:
      - owncloud_net

networks:
  owncloud_net:
    driver: bridge
